version: "3.9"
services:
    password:
        image: ${REGISTRY}/password-react:${IMAGE_TAG}
        environment:
            NODE_ENV: production
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.password-http.rule=Host(`pwd.herman.team`)
                - traefik.http.routers.password-http.entrypoints=http
                - traefik.http.routers.password-http.middlewares=https-redirect
                - traefik.http.routers.password-https.rule=Host(`pwd.herman.team`)
                - traefik.http.routers.password-https.entrypoints=https
                - traefik.http.routers.password-https.tls=true
                - traefik.http.routers.password-https.tls.certresolver=le
                - traefik.http.services.password.loadbalancer.server.port=80

networks:
    traefik-public:
        external: true