version: "3.9"
services:
    password:
        image: ${REGISTRY}/password-react:${IMAGE_TAG}
        environment:
            NODE_ENV: production
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.password.rule=Host(`pwd.herman.team`)
                - traefik.http.services.password.loadBalancer.server.port=80
                - traefik.http.middlewares.password-redirect.redirectRegex.regex=^(https?://)www.pwd.herman.team/(.*)$$
                - traefik.http.middlewares.password-redirect.redirectRegex.replacement=$${1}pwd.herman.team/$${2}
                - traefik.http.middlewares.password-redirect.redirectRegex.permanent=true
                - traefik.http.routers.password.middlewares=password-redirect,secure-headers
                - traefik.http.routers.password.entrypoints=https
                - traefik.http.routers.password.tls=true
                - traefik.http.routers.password.tls.certResolver=letsEncrypt

networks:
    traefik-public:
        external: true