version: "3.9"
services:
    traefik:
        image: "traefik:2.9"
        container_name: "traefik"
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    react-node:
        build:
            context: react/docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            NODE_ENV: development
        volumes:
            - ./react:/app:rw
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true

    react-node-cli:
        build:
            context: react/docker/development/node
        volumes:
            - ./react:/app

    react:
        build:
            context: react/docker/development/nginx
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.react.entrypoints=http
            - traefik.http.routers.react.rule=Host(`password.localhost`) || Host(`www.password.localhost`)
            - traefik.http.services.react.loadBalancer.server.port=80

networks:
    traefik-public:
        name: traefik-public